"""Import a Google Desktop OAuth client and optionally authorize this server."""

import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1] / "main/xiaozhi-server"
sys.path.insert(0, str(PROJECT))

from config.cloud_recovery import RecoveryError
from config.config_store import canonical_bytes
from config.recovery_cli import SafeParser
from config.recovery_oauth import (
    OAuthStorageError, add_oauth_arguments, credential_payload, install_oauth_file,
    load_oauth_client, obtain_credentials,
)


INSTRUCTIONS = """One-time Google application setup (use the same client on every box):
1. Open https://console.cloud.google.com/ and select/create a project.
2. Enable Google Drive API in APIs & Services > Library.
3. Configure Google Auth Platform > Branding and Audience.
   For personal Gmail choose External; add your email under Test users if Testing.
4. In Data Access add https://www.googleapis.com/auth/drive.file.
5. In Clients create a Desktop app client and download its JSON file.
6. Import it: python scripts/setup_google_drive.py --import-client FILE --authorize
   Run this command from the repository root using your server Python environment.
   On SSH, add --ssh-target user@server for a ready-to-copy tunnel command.

Google registration cannot be generated by user login. This command installs the
downloaded client as data/oauth-client.json; login creates data/drive-credentials.json.
For existing Cloud State, reuse the original application's client, not a new one.
Do not commit either file. Existing files are never replaced by this setup helper.
"""


def main(argv=None, *, credential_loader=obtain_credentials):
    parser = SafeParser(description=__doc__)
    parser.add_argument("--import-client", type=Path, help="Downloaded Desktop app JSON; installed once without overwriting an existing client")
    parser.add_argument("--authorize", action="store_true", help="Login and save credentials for provisioning/restore")
    add_oauth_arguments(parser)
    try:
        args = parser.parse_args(argv)
        if args.import_client is None and not args.authorize:
            print(INSTRUCTIONS)
            return 0
        client_path = PROJECT / "data/oauth-client.json"
        credentials_path = PROJECT / "data/drive-credentials.json"
        config = load_oauth_client(args.import_client or client_path)
        if credentials_path.exists():
            payload = credential_payload(credentials_path.read_bytes())
            if payload.get("type") != "authorized_user" or payload["client_id"] != config["installed"]["client_id"]:
                raise OAuthStorageError()
        if args.import_client is not None:
            install_oauth_file(client_path, canonical_bytes(config))
            print("Desktop OAuth client: installed (data/oauth-client.json).")
        if args.authorize:
            if credentials_path.exists():
                print("Existing credentials kept; no login required. Runtime will refresh them when needed.")
            else:
                content, _ = credential_loader(client_path=client_path,
                    open_browser=False if args.no_browser else None, oauth_port=args.oauth_port,
                    oauth_timeout=args.oauth_timeout, ssh_target=args.ssh_target)
                payload = credential_payload(content)
                if payload.get("type") != "authorized_user" or payload["client_id"] != config["installed"]["client_id"]:
                    raise OAuthStorageError()
                install_oauth_file(credentials_path, canonical_bytes(payload))
                print("Google credentials: saved privately (data/drive-credentials.json).")
            print("OAuth ready. Provision or restore Cloud State next; provider and node identity are unchanged.")
        return 0
    except RecoveryError as error:
        print(error.message, file=sys.stderr)
        return 4
    except Exception:
        print(OAuthStorageError.message, file=sys.stderr)
        return 4


if __name__ == "__main__":
    raise SystemExit(main())
